Se agrega Logica ECR URI ambiente y el discpach a DevOps

diff --git a/.github/workflows/ci-pipeline-payments-service.yml b/.github/workflows/ci-pipeline-payments-service.yml
--- a/.github/workflows/ci-pipeline-payments-service.yml
+++ b/.github/workflows/ci-pipeline-payments-service.yml
@@ -6,11 +6,6 @@ on:
       - develop
       - staging
       - main
-  pull_request:
-    branches:
-      - develop
-      - staging
-      - main
 
 jobs:
   build-test-deploy:
@@ -64,17 +59,41 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
           aws-region: ${{ secrets.AWS_REGION }}
+      
+      - name: Obtener URI_ECR de entorno
+        run: |
+          if [[ "${{ github.ref_name }}" == "main" ]]; then
+            echo "ECR_URI=${{ secrets.ECR_URI_PAYMENTS_PROD }}" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
+            echo "ECR_URI=${{ secrets.ECR_URI_PAYMENTS_STAGING }}" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
+            echo "ECR_URI=${{ secrets.ECR_URI_PAYMENTS_DEV }}" >> $GITHUB_ENV
+          else
+            echo "Rama Invalida"
+            exit 1
+          fi
  
       - name: Login to Amazon ECR
         run: |
-           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_URI_PAYMENTS }}
+           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_URI }}
  
       - name: Build Docker image
         run: |
            IMAGE_TAG=${{ github.sha }}
-           docker build -t ${{ secrets.ECR_URI_PAYMENTS }}:$IMAGE_TAG .
+           docker build -t ${{ env.ECR_URI }}:$IMAGE_TAG .
            echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
  
       - name: Push Docker image to ECR
         run: |
-           docker push ${{ secrets.ECR_URI_PAYMENTS }}:${{ env.IMAGE_TAG }}
+           docker push ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}
+
+      - name: Get repository name
+        run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
+      
+      - name: Terraform deployy
+        uses: peter-evans/repository-dispatch@v2
+        with:
+          repository: Obligatorio-DevOps-Corbalan-Arzuaga/DevOps
+          token: ${{ secrets.DISPATCH_TOKEN }} # No sirve el github token, ya que es para un repo remoto, necesita un PAT token
+          event-type: terraform # Debe coincidir con el que espera el workfloww en DevOps
+          client-payload: '{"docker-image": "${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}", "environment": "${{ github.ref_name }}", "project": "${{ env.REPO_NAME }}"}' 
